### ISSUE TITLE
Package distribution

### ISSUE THREAD

**Issue by miykael** [miykael/parcellation_fragmenter#3]
I'm not sure where this package best fit. Should it be added to a particular library (nibabel, nilearn), should it be a standalone pip package, a command line interface, a mybinder notebook that runs in the cloud or just a simple script?

Any input is very welcomed and the creation of a clearer interface would be amazing. I.e. the definition of input parameters, validation of them, writing some tests etc. would be greatly appreciated!

**Comment by ctoroserey** [comment]
I like the idea of having it as a standalone pip-installable package, but adding it to something like nibabel would also sound good. Not sure how tough it would be to do the latter, though.

**Comment by miykael** [comment]
I think the installation with `pip install -e` actually answers this issue.
