### ISSUE TITLE
Null model generation

### ISSUE THREAD

**Issue by ctoroserey** [miykael/parcellation_fragmenter#7]
The idea is to create a function that will apply slight rotations to the parcellation after it has been computed. Kristian's analogy works great here: think of the parcellation as a blanket that you're covering the spherical surface mesh with. A null model would make slight changes of the position of the blanket while maintaining the position of the sphere.

We have thought of two options so far:

1) Have an affine transformation matrix so we only change its rotation element. Permute the rotation degree, apply to the coordinates, but retain the faces (and apply nearest neighbors to the original so that some order is retained)

2) Do a simple markov model, such that for each label you check the label of its neighbors and compute the probability of shifting to the label of one of the neighbors. This would operate on the edges of each parcel, but has the chance of changing the form of the parcellation a bit.

We will start with number 2 for simplicity, and I will begin work on it.

**Comment by miykael** [comment]
Linking to https://github.com/miykael/parcellation_fragmenter/issues/6 as it covers the same issue.
